
documentos_Sika = [ '.\FT_SIKA\IgolEcoasfalto.pdf',
    '.\FT_SIKA\Igol S.pdf',
    '.\FT_SIKA\Igol®-2.pdf',
    '.\FT_SIKA\Igolflex Fachada.pdf',
    '.\FT_SIKA\Igolflex Preto.pdf',
    '.\FT_SIKA\Impermur_Sikagard.pdf',
    '.\FT_SIKA\Impersika.pdf',
    '.\FT_SIKA\PK Premium Superflex.pdf',
    '.\FT_SIKA\Sika 1.pdf',
    '.\FT_SIKA\Sika 2.pdf',
    '.\FT_SIKA\Sika 3 Plus.pdf',
    '.\FT_SIKA\Sika Chapisco Plus.pdf',
    '.\FT_SIKA\Sika Concreto Forte.pdf',
    '.\FT_SIKA\Sika Eco Primer.pdf',
    '.\FT_SIKA\Sika Monotop 123 Rodapé.pdf',
    '.\FT_SIKA\Sika Multiseal Primer.pdf',
    '.\FT_SIKA\SikaCryl 203.pdf',
    '.\FT_SIKA\Sikadur 32.pdf',
    '.\FT_SIKA\Sikadur 512.pdf',
    '.\FT_SIKA\Sikadur Epoxi.pdf',
    '.\FT_SIKA\Sikafill Rápido Power.pdf',
    '.\FT_SIKA\Sikafill Rápido.pdf',
    '.\FT_SIKA\Sikaflex 1A Plus.pdf',
    '.\FT_SIKA\Sikaflex Construction.pdf',
    '.\FT_SIKA\Sikaflex Universal.pdf',
    '.\FT_SIKA\Sikagrout 250.pdf',
    '.\FT_SIKA\Sikatop 100.pdf',
    '.\FT_SIKA\Sikatop 107.pdf',
    '.\FT_SIKA\Sikatop Flex.pdf'
    ]

documentos_mc = ['.\FT - MC BAUCHEMIE\Areia MC 120.pdf', '.\FT - MC BAUCHEMIE\Areia SK1.pdf',
                 '.\FT - MC BAUCHEMIE\Areia SK2.pdf', '.\FT - MC BAUCHEMIE\D 11.pdf',
                 '.\FT - MC BAUCHEMIE\D 15.pdf', '.\FT - MC BAUCHEMIE\Emcekrete 40.pdf',
                 '.\FT - MC BAUCHEMIE\Emcekrete 50 Fast.pdf', '.\FT - MC BAUCHEMIE\Emcekrete 50.pdf',
                 '.\FT - MC BAUCHEMIE\Emcekrete EP.pdf', '.\FT - MC BAUCHEMIE\Emcekrete.pdf',
                 '.\FT - MC BAUCHEMIE\Hydro 1.pdf', '.\FT - MC BAUCHEMIE\M 12 HP.pdf',
                 '.\FT - MC BAUCHEMIE\M 21.pdf', '.\FT - MC BAUCHEMIE\M 29 HP.pdf',
                 '.\FT - MC BAUCHEMIE\M 32.pdf', '.\FT - MC BAUCHEMIE\MC-CarbonFiber Sheets.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Fast Block.pdf', '.\FT - MC BAUCHEMIE\MC-Flex 450 VE.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Flex PU 25.pdf', '.\FT - MC BAUCHEMIE\MC-Flex PU 40.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Flex PU Construção.pdf', '.\FT - MC BAUCHEMIE\MC-Injekt 2300 FLOW.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Proof 500.pdf', '.\FT - MC BAUCHEMIE\MC-Proof 900 EL.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Proof 2200.pdf', '.\FT - MC BAUCHEMIE\MC-Proof Multi.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Quicktop.pdf', '.\FT - MC BAUCHEMIE\MC-RIM Protect.pdf',
                 '.\FT - MC BAUCHEMIE\MC-Solid 1300.pdf', '.\FT - MC BAUCHEMIE\MC-Water Stop.pdf',
                 '.\FT - MC BAUCHEMIE\Murafan 39.pdf', '.\FT - MC BAUCHEMIE\Nafufill GM 2.pdf',
                 '.\FT - MC BAUCHEMIE\Quickset.pdf']

documentos_vedacit = ['.\FT - VEDACIT\ACQUELLA.pdf', '.\FT - VEDACIT\BIANCO PRO.pdf',
                      '.\FT - VEDACIT\BIANCO.pdf', '.\FT - VEDACIT\COMPENSADOR DE RETRAÇÃO.pdf',
                      '.\FT - VEDACIT\DESMOLDANTE.pdf', '.\FT - VEDACIT\EMULSÃO ASFÁLTICA.pdf',
                      '.\FT - VEDACIT\MANTA ASFÁLTICA TIPO II B ALUMINIO GLASS.pdf', '.\FT - VEDACIT\MANTA ASFÁLTICA TIPO II B ALUMINIO POLIÉSTER.pdf',
                      '.\FT - VEDACIT\MANTA ASFÁLTICA TIPO II B POLIÉSTER.pdf', '.\FT - VEDACIT\MANTA ASFÁLTICA TIPO III B PP.pdf',
                      '.\FT - VEDACIT\NEUTROL ACQUA.pdf', '.\FT - VEDACIT\NEUTROL PRO.pdf',
                      '.\FT - VEDACIT\NEUTROL.pdf', '.\FT - VEDACIT\PENTROL.pdf',
                      '.\FT - VEDACIT\TINTA ALCATRÃO.pdf', '.\FT - VEDACIT\Vedacit Pro - Aditivo impermeabilizante.pdf',
                      '.\FT - VEDACIT\VEDACIT.pdf', '.\FT - VEDACIT\VEDALIT.pdf',
                      '.\FT - VEDACIT\VEDAPREN BRANCO.pdf', '.\FT - VEDACIT\VEDAPREN FAST.pdf',
                      '.\FT - VEDACIT\VEDAPREN PAREDE.pdf', '.\FT - VEDACIT\VEDAPREN.pdf',
                      '.\FT - VEDACIT\VEDATOP FLEX.pdf', '.\FT - VEDACIT\VEDATOP RODAPÉ.pdf',
                      '.\FT - VEDACIT\VEDATOP.pdf']

documentos_viapol = ['.\FT - VIAPOL\\ft-contra-umidade-29092022-nf.pdf', '.\FT - VIAPOL\\ft-eucon-vandex-am10-07.pdf',
                     '.\FT - VIAPOL\\ft-fuseprotec-parede-07-03-2023-rev04.pdf', '.\FT - VIAPOL\\ft-heydicryl-mastique-07-2021.pdf',
                     '.\FT - VIAPOL\\ft-tapa-goteira-rev13-11-2023.pdf', '.\FT - VIAPOL\\ft-tuf-strand-max-ten-21-10-2020.pdf',
                     '.\FT - VIAPOL\\ft-tuf-strand-sf-16-10-2020.pdf', '.\FT - VIAPOL\\ft-vedalage-branco-31-05-2021.pdf',
                     '.\FT - VIAPOL\\ft-viafix-01-06-13.pdf', '.\FT - VIAPOL\\ft-viaplus-1000-06112024.pdf',
                     '.\FT - VIAPOL\\ft-viaplus-5000-04052023-nf.pdf', '.\FT - VIAPOL\\ft-viaplus-7000-04052023-nf.pdf']

documentos_dryko = ['.\FT - DRYKO\FICHA-TÉCNICA-DRYKOELASTIC-REVISADO_06_2024.pdf', '.\FT - DRYKO\FICHA-TÉCNICA-DRYKOFITA-ALUMÍNIO-1.pdf',
                    '.\FT - DRYKO\FICHA-TÉCNICA-DRYKOFIX.pdf', '.\FT - DRYKO\FICHA-TÉCNICA-DRYKOMANTA-POLIALUM-1.pdf',
                    '.\FT - DRYKO\FICHA-TÉCNICA-DRYKOMANTAFLEX-3.pdf', '.\FT - DRYKO\FICHA-TÉCNICA-DRYKOPRIMER-ACQUA-09.2024-1.pdf',
                    '.\FT - DRYKO\FICHA-TÉCNICA-PINTURA-EMBORRACHADA-VEDATUDO-1.pdf', '.\FT - DRYKO\FICHA-TÉCNICA-SPRAY-VEDATUDO-IMPERMEABILIZANTE.pdf',
                    '.\FT - DRYKO\FICHA-TÉCNICA-TIRA-COLA.pdf', '.\FT - DRYKO\FITA-VEDATUDO-ULTRADRY.pdf']

documentos_denver = ['.\FT - DENVER\\003-denvertec-540-flex-rev19_2023072017390152Oew5Cory.pdf', '.\FT - DENVER\\096-denverpoxi-rev12_20220919110853OBgbG89rz4.pdf',
                     '.\FT - DENVER\\103-denver-repele-acqua-rev08_20210331192900v1N11l27X7.pdf', '.\FT - DENVER\\115-denver-imperblack-rev13a_20230622120906LxTTnHOqAz.pdf',
                     '.\FT - DENVER\\172-denvercal-rev10_20240806201140FzNzn79oHa.pdf', '.\FT - DENVER\\184-denver-desforma-rev06_20210331185555CbKsksudRu.pdf',
                     '.\FT - DENVER\denvertec-100.pdf']